### ISSUE TITLE
errror when adding in stellar properties

### ISSUE THREAD

**Issue by toribonidie** [franpoz/SHERLOCK#107]
Hi!

I am trying to use SHERLOCK to search for planetary transits around red clump stars. I am receiving an error message when I try to input stellar properties to my .yaml file. I am attaching both the .yaml file and the output file with the error message. It seems that it is creating a very short period grid (19.503 - 32.968 days) to search in, and I am unsure why. Please let me know if you can look into this issue, as I've been unable to fix it on my own so far and would really love to keep using your PlanetHunters suite for my research.

Thank you so much!

[test.yaml.txt](https://github.com/franpoz/SHERLOCK/files/11160707/test.yaml.txt)

[sherlock_test.out.txt](https://github.com/franpoz/SHERLOCK/files/11160708/sherlock_test.out.txt)

**Comment by toribonidie** [comment]
Hi Martín!

Thank you so much for the quick response! It does seem that the issue with the period grid is stemming from the TLS algorithm, but I am not sure if that is what is causing the error message. The error I am getting says:

`Traceback (most recent call last):
  File "/home/veb19/miniconda3/envs/sherlock/lib/python3.8/site-packages/sherlockpipe/search/sherlock.py", line 260, in __run_object
    for index in np.arange(len(signal_selection.transit_result.t0s)):
TypeError: len() of unsized object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/veb19/miniconda3/envs/sherlock/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/veb19/miniconda3/envs/sherlock/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/veb19/miniconda3/envs/sherlock/lib/python3.8/site-packages/sherlockpipe/__main__.py", line 12, in <module>
    run_search(args.properties, args.explore, args.results_dir)
  File "/home/veb19/miniconda3/envs/sherlock/lib/python3.8/site-packages/sherlockpipe/search/run.py", line 326, in run_search
    sherlock.Sherlock(sherlock_targets, explore, cache_dir=cache_dir, results_dir=results_dir).run()
  File "/home/veb19/miniconda3/envs/sherlock/lib/python3.8/site-packages/sherlockpipe/search/sherlock.py", line 205, in run
    self.__run_object(sherlock_target)
  File "/home/veb19/miniconda3/envs/sherlock/lib/python3.8/site-packages/sherlockpipe/search/sherlock.py", line 340, in __run_object
    logging.exception(str(e))
  File "/home/veb19/miniconda3/envs/sherlock/lib/python3.8/logging/__init__.py", line 2057, in exception
    error(msg, *args, exc_info=exc_info, **kwargs)
  File "/home/veb19/miniconda3/envs/sherlock/lib/python3.8/logging/__init__.py", line 2049, in error
    root.error(msg, *args, **kwargs)
  File "/home/veb19/miniconda3/envs/sherlock/lib/python3.8/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'exc_info'`

I will keep looking into this! Thank you for your help.

**Comment by toribonidie** [comment]
Hi Martin! 

I am so sorry to keep bugging you, I have one (hopefully last) question.

When I manually input my minimum and maximum periods in the .yaml file, sherlock reads it in, but then they get overriden by the values computed by TLS. I am attaching the output file that shows this.

I think that the minimum period TLS is calculating is the first possible period after the Roche Limit of the given star, given by the equation `fmax =pGMs/(3Rs)3/(2π)`, as you previously pointed out. But I think they are hard coding in the density values to achieve this equation. Because I am working with Red Clump stars, which are much less dense, I am getting really inaccurate values for the minimum period possible. 

If you know how to prevent TLS from overriding the period grid I manually input, please let me know! If not, I can just raise an issue on the TLS github page instead!

Thanks so much,
Tori 
[sherlock_test.txt](https://github.com/franpoz/SHERLOCK/files/11194147/sherlock_test.txt)

**Comment by toribonidie** [comment]
Hi Martin,

Thanks for your quick response! In their paper, they say that the most short- period (high-frequency) circumstellar orbit is given by 
```math
f_{max} = \frac{\sqrt{GM_{s}/(3R_{s}})^{3}}{2\pi}
```
where the $3R_{s}$ term is calculated from the Roche limit, assuming a pessimistic density of $\rho_{p} = 1  g/cm^{3}$. They did not show a derivation for this formula in their paper, but I think they are starting with Kepler's 3rd law

```math
f_{max} = 1/P =  \frac{\sqrt{GM_{s}/(a})^{3}}{2\pi}
```

And they are using the roche limit to calculate the semi major axis. For a rigid transiting body, the roche limit is given by,

```math
a = R_{s} (2 \frac{\rho_{s}}{\rho_{p}})^{1/3}.
```

Or, for a fluid transiting body, the roche limit is given by,

```math
a \approx 2.44R_{s} (\frac{\rho_{s}}{\rho_{p}})^{1/3}.
```

They are assuming  $\rho_{p} = 1  g/cm^{3}$, but I do not see them making any assumption about $\rho_{s}$. Now, if use this assumption of planet density and I plug in my value for a typical density of a RC star (0.002 $g/cm^{3}$), I get 

```math
a^{3} = 0.004 R_{s}^{3} 
```
for a rigid body and

```math
a^{3} = 0.03 R_{s}^{3} 
```

These are both  extremely different from the value they are getting for their $a^3$ term, which is $(3R_{s})^3$. My best guess is that maybe they are inputing a typical density for a solar mass star (~1.4 $g/cm^{3}$ for the sun), because that would produce an $a^{3}$ term that is roughly $(3R_{s})^3$.

I don't see anything in the paper that makes this assumption, so I could be misinterpreting the way they are deriving their equation for $f_{max}$. This formula is restricting the period range that Sherlock searches, but I believe shorter periods are physically possible. 

Please let me know if this makes sense.  Thank you so much!

**Comment by toribonidie** [comment]
Perfect! Thank you so much.
