### ISSUE TITLE
LATTE vetting printing exception when executed for object without TOI

### ISSUE THREAD

**Issue by martindevora** [franpoz/SHERLOCK#46]
Example:
`vet.py --object_dir MIS_TIC_307210830_all --candidate 5`

```
Traceback (most recent call last):
  File "/home/martin/git_repositories/sherlockpipe/sherlockpipe/vet.py", line 162, in __process
    dec, self.args)
  File "/home/martin/git_repositories/sherlockpipe/watson/lib/python3.6/site-packages/LATTE/LATTEbrew.py", line 363, in brew_LATTE
    ldv.LATTE_DV(tic, indir, syspath, transit_list, sectors_all, target_ra, target_dec, tessmag, teff, srad, [0], [0], tpf_corrupt, astroquery_corrupt, FFI = False,  bls = False, model = model, mpi = args.mpi)
  File "/home/martin/git_repositories/sherlockpipe/watson/lib/python3.6/site-packages/LATTE/LATTE_DV.py", line 89, in LATTE_DV
    TOI = (float(TOIpl["Full TOI ID"]))
  File "/home/martin/git_repositories/sherlockpipe/watson/lib/python3.6/site-packages/pandas/core/series.py", line 129, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'float'>
couldn't download TP but continue anyway
```

**Comment by martindevora** [comment]
LATTE is not used anymore
