### ISSUE TITLE
Math domain error in calculate_planet_radius

### ISSUE THREAD

**Issue by martindevora** [franpoz/SHERLOCK#70]
```
GLOBAL_TWO_MIN_IDS:
  'TIC 273369281': "all"
AUTO_DETREND_ENABLED: TRUE
INITIAL_HIGH_RMS_MASK: TRUE
INITIAL_SMOOTH_ENABLED: TRUE
BEST_SIGNAL_ALGORITHM: 'quorum'
DETRENDS_NUMBER: 8
DETREND_CORES: 15
CPU_CORES: 15
MAX_RUNS: 3
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sherlockpipe/sherlock.py", line 326, in __run_object
    self.report[sherlock_id], wl)
  File "/usr/local/lib/python3.6/site-packages/sherlockpipe/sherlock.py", line 717, in __analyse
    transit_results = self.__identify_signals(object_info, time, lcs, flux_err, star_info, transits_min_count, wl, id_run, cadence, report)
  File "/usr/local/lib/python3.6/site-packages/sherlockpipe/sherlock.py", line 829, in __identify_signals
    r_planet = self.__calculate_planet_radius(star_info, transit_result.depth)
  File "/usr/local/lib/python3.6/site-packages/sherlockpipe/sherlock.py", line 903, in __calculate_planet_radius
    return star_info.radius * math.sqrt(depth / 1000) / 0.0091577
ValueError: math domain error
```

**Comment by martindevora** [comment]
The mean depth retienes by TLS is negativo, tus, matt Romain error when domingo sqrt.
