### ISSUE TITLE
All-NaN slice encountered when all signals are nan in quorum

### ISSUE THREAD

**Issue by martindevora** [franpoz/SHERLOCK#75]
SEARCH OF SIGNALS - Run 10
=================================
win_size    Period    Per_err   N.Tran  Mean Depth (ppt)  T. dur (min)  T0            SNR         SDE         FAP           Border_score    Matching OI   Harmonic    Planet radius (R_Earth)  Rp/Rs     Semi-major axis   Habitability Zone   
Transit Least Squares TLS 1.0.25 (04 June 2020)
Creating model cache for 37 durations
Searching 12427 data points, 24071 periods from 0.5 to 12.101 days
Using 7 of 8 CPU threads
PDCSAP_FLUX nan       -5.800330 nan     nan               nan           0.0000        nan         0.000       nan           0.00            nan           -           nan                      nan       nan               -                   
Transit Least Squares TLS 1.0.25 (04 June 2020)
Creating model cache for 37 durations
Searching 12427 data points, 24071 periods from 0.5 to 12.101 days
Using 7 of 8 CPU threads
0.1607      nan       -5.800330 nan     nan               nan           0.0000        nan         0.000       nan           0.00            nan           -           nan                      nan       nan               -                   
All-NaN slice encountered
Traceback (most recent call last):
  File "/home/martin/git_repositories/sherlockpipe/sherlockpipe/sherlock.py", line 346, in __run_object
    self.report[sherlock_id], wl)
  File "/home/martin/git_repositories/sherlockpipe/sherlockpipe/sherlock.py", line 788, in __analyse
    .select(transit_results, self.snr_min, self.detrend_method, wl)
  File "/home/martin/git_repositories/sherlockpipe/sherlockpipe/scoring/QuorumSnrBorderCorrectedSignalSelector.py", line 41, in select
    best_signal_snr_index = np.nanargmax(corrected_snrs)
  File "<__array_function__ internals>", line 6, in nanargmax
  File "/home/martin/.local/lib/python3.6/site-packages/numpy/lib/nanfunctions.py", line 551, in nanargmax
    raise ValueError("All-NaN slice encountered")
ValueError: All-NaN slice encountered
All-NaN slice encountered

Process finished with exit code 0

**Comment by martindevora** [comment]
We need to test this somehow but it should be fixed with the next version.
